stages:
  - build
  - deploy

variables:
  IMAGE_NAME: vardhangollapalli/my-automation-app

build-image:
  stage: build
  tags:
    - local-runner
  script:
    - docker build -t ${IMAGE_NAME}:${CI_PIPELINE_ID} .
    - echo $DOCKER_HUB_PASSWORD | docker login -u $DOCKER_HUB_USERNAME --password-stdin
    - docker push ${IMAGE_NAME}:${CI_PIPELINE_ID}

deploy-k8s:
  stage: deploy
  tags:
    - local-runner
  script:
    - kubectl config use-context minikube
    - kubectl set image deployment/my-automation-app-deployment my-automation-app=${IMAGE_NAME}:${CI_PIPELINE_ID}